### PR TITLE
Added p-value simulation and violin plot - not yet run

### PR DESCRIPTION
**Pull request by prpatil**
The code is at the bottom of the .Rmd file...have not added the accompanying figures to the "Results" folder yet.

### CODE REVIEW

**Comment by jtleek** [comment]
You should try running to add it to the plot and save the figures in a future pr

**Comment by prpatil** [comment]
Ah I don't have this "font = Lato" thing on Windows apparently...otherwise
it pretty much works

**Comment by jtleek** [comment]
Dude you gotta download the lato font. Then you can load it. You can get it from Google fonts.

**Comment by prpatil** [comment]
Ya I did but I still get weird unknown font size errors and none of the
figures get axes when the PDFs are made. Windows, man

**Comment by jtleek** [comment]
Windows!!!!

Ok, I can recompile. 

But all the code is there otherwise?

**Comment by prpatil** [comment]
Yeah...just add pdf(...) and dev.off() commands around the two plots I
added at the end so that they write to the results folder. Should work. We
can decide what to do about the violin plots. I added text to overleaf, too.

**Pull request merged**
